name: qaos
version: .
date: 
description: Interfacing the QaoS database from GAP

authors:
    - name: Sebastian Freundt
      url: http://www.math.tu-berlin.de/~freundt
    - name: Sebastian Pauli
      url: http://www.math.tu-berlin.de/~pauli

maintainers:
    - name: Markus Pfeiffer
      url: http://www.morphism.de/~markusp/

GAP: ">= 4.3"

www: http://qaos.math.tu-berlin.de/qaos/qaos.scm
readme: http://www.math.tu-berlin.de/~kant/download/gap/qaos.README
packageinfo: http://www.math.tu-berlin.de/~kant/download/gap/qaos.PackageInfo.g

downloads:
    - name: .tar.bz2
      url: http://www.math.tu-berlin.de/~kant/download/gap/qaos-..tar.bz2

abstract: The <span class="pkgname">QaoS</span> package provides gateway functions to access the QaoS databases of algebraic objects in Berlin. <span class="pkgname">QaoS</span> is primarily intended to query for transitive groups or algebraic number fields and turn retrieved results into GAP objects for further computing.

status: deposited
doc-html: doc/qaos.html
doc-pdf: doc/qaos.pdf
