name: qaos
version: 1.3
date: 11/11/2016
description: Interfacing the QaoS database from GAP

authors:
    - name: Sebastian Freundt
      url: http://www.math.tu-berlin.de/~freundt
    - name: Sebastian Pauli
      url: http://www.math.tu-berlin.de/~pauli

maintainers:
    - name: Markus Pfeiffer
      url: http://www.morphism.de/~markusp/

GAP: ">= 4.3"

www: https://gap-packages.github.io/qaos
readme: https://gap-packages.github.io/qaos/README
packageinfo: https://gap-packages.github.io/qaos/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/qaos/releases/download/v1.3/qaos-1.3.tar.gz

abstract: The <span class="pkgname">QaoS</span> package provides gateway functions to access the QaoS databases of algebraic objects in Berlin. <span class="pkgname">QaoS</span> is primarily intended to query for transitive groups or algebraic number fields and turn retrieved results into GAP objects for further computing.

status: deposited
doc-html: doc/qaos.html
doc-pdf: doc/qaos.pdf
